--- |
  dataset:
    class_weights:
    - 55437630
    - 320797
    - 541736
    - 2578735
    - 3274484
    - 552662
    - 184064
    - 78858
    - 240942562
    - 17294618
    - 170599734
    - 6369672
    - 230413074
    - 101130274
    - 476491114
    - 9833174
    - 129609852
    - 4506626
    - 1168181
    dataset_path: /home/yiling/d2T/intel2020/datasets/semanticKITTI/data_odometry_velodyne/dataset/sequences_0.06
    test_result_folder: ./test
    test_split_number: 11
    training_split:
    - '00'
    validation_split:
    - '08'
  model:
    ckpt_path: ./ml3d/torch/checkpoint/randlanet_semantickitti2.pth
    d_feature: 8
    d_in: 3
    d_out:
    - 16
    - 64
    - 128
    - 256
    k_n: 16
    num_classes: 19
    num_layers: 4
    num_points: 45056
    num_sub_points:
    - 11264
    - 2816
    - 704
    - 176
    sub_grid_size: 0.06
    sub_sampling_ratio:
    - 4
    - 4
    - 4
    - 4
  pipeline:
    adam_lr: 0.01
    batch_size: 6
    val_batch_size: 24
    test_batch_size: 2
    learning_rate: 0.01
    main_log_dir: ./logs
    max_epoch: 100
    model_name: RandLANet
    save_ckpt_freq: 5
    scheduler_gamma: 0.95
    train_sum_dir: train_log
