dataset:
  name: Scannet
    # [scenes|frames] Use point clouds from entire scenes or individual frames
  portion: frames
  # path/to/your/dataset
  dataset_path: /mnt/beegfs/tier1/vcl-nfs-work/ssheorey/Open3D/Datasets/ScanNet-cache
  cache_dir: ./logs/cache
  #  steps_per_epoch_train: 5000

model:
  name: PointPillars
  # path/to/your/checkpoint
  ckpt_path:

  point_cloud_range: [-2, -1.5, 0, 2, 1.5, 3.5]   # TBC
  classes: [
    'cabinet', 'bed', 'chair', 'sofa', 'table', 'door', 'window',
    'bookshelf', 'picture', 'counter', 'desk', 'curtain',
    'refrigerator', 'showercurtrain', 'toilet', 'sink', 'bathtub',
    'garbagebin'
  ]

  loss:
    focal:
      gamma: 2.0
      alpha: 0.25
      loss_weight: 1.0
    smooth_l1:
      beta: 0.11
      loss_weight: 2.0
    cross_entropy:
      loss_weight: 0.2

  voxelize:
    max_num_points: 8
    voxel_size: &vsize
      [0.025, 0.025, 4]             # TBC
    max_voxels: [16000, 19200]      # [P_train, P_test]

  voxel_encoder:
    in_channels: 3
    feat_channels: [64]
    voxel_size: *vsize

  scatter:
    in_channels: 64
    output_shape: [120, 160]

  backbone:
    in_channels: 64
    out_channels: [64, 128, 256]
    layer_nums: [3, 5, 5]
    layer_strides: [2, 2, 2]

  neck:
    in_channels: [64, 128, 256]
    out_channels: [128, 128, 128]
    upsample_strides: [1, 2, 4]
    use_conv_for_no_stride: false

  head:
    in_channels: 384
    feat_channels: 384
    nms_pre: 100
    score_thr: 0.1
    ranges: [                   # TBC
      [-2, -1.5, 0, 2, 1.5, 3.5]
    ]
    sizes: [
      [0.29932949, 0.33707996, 0.35533315],
      [0.6632437, 1.52458419, 0.75902226],
      [2.04830034, 0.49337864, 1.91016245],
      [2.27818346, 1.64360089, 1.05379309],
      [0.83067288, 4.01659373, 1.09979817],
      [0.33988471, 0.56968156, 1.49112693],
      [1.08657705, 0.90542837, 0.74840754],
      [1.26724763, 2.25418469, 0.83717565],
      [0.56112528, 2.10178122, 1.99214106],
      [0.61355279, 0.61735222, 0.87973592],
      [3.653598, 0.70631018, 1.46367865],
      [0.2879446, 1.02800628, 1.93086022],
      [1.91449086, 0.55880966, 0.78050747],
      [1.24382453, 7.25542195, 1.30830698],
      [0.96003801, 0.3141197, 1.97914434],
      [0.61519117, 0.57231487, 0.46996917],
      [1.01003021, 0.23239203, 1.09051603],
      [0.19386983, 0.86455952, 0.81426984],
      [3.0138944, 3.4347804, 0.75693413],
      [0.45105186, 2.69681101, 0.85638664]
    ]

    rotations: [0, 1.57]
    iou_thr: [
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
      [0.35, 0.5],
    ]                # TBC

  augment:
    PointShuffle: true
    ObjectRangeFilter: true

pipeline:
  name: ObjectDetection
  test_compute_metric: true
  batch_size: 28
  val_batch_size: 28
  save_ckpt_freq: 5
  max_epoch: 200
  main_log_dir: ./logs
  train_sum_dir: ./logs/train_log
  grad_clip_norm: 2

  optimizer:
    lr: 0.001
    betas: [0.95, 0.99]
    weight_decay: 0.01

  # evaluation properties
  overlaps: [
    0.5, 0.5, 0.5,
    0.5, 0.5, 0.5,
    0.5, 0.5, 0.5,
    0.5, 0.5, 0.5,
    0.5, 0.5, 0.5,
    0.5, 0.5, 0.5
  ]                     # TBC
  similar_classes: {
  }
  difficulties: [0, 1, 2, 3, 4]
