dataset:
  name: Scannet
  # path/to/your/dataset
  dataset_path: /home/ssheorey/Datasets/ScanNet/npy-tiny
  cache_dir: ./logs/cache
  steps_per_epoch_train: 5000

model:
  name: PointPillars
  # path/to/your/checkpoint
  ckpt_path:

  point_cloud_range: [-3, -3, 0, 3, 3, 6]   # TBC
  classes: [
      'cabinet', 'bed', 'chair', 'sofa', 'table', 'door', 'window',
      'bookshelf', 'picture', 'counter', 'desk', 'curtain',
      'refrigerator', 'showercurtrain', 'toilet', 'sink', 'bathtub',
      'garbagebin'
  ]

  loss:
    focal:
      gamma: 2.0
      alpha: 0.25
      loss_weight: 1.0
    smooth_l1:
      beta: 0.11
      loss_weight: 2.0
    cross_entropy:
      loss_weight: 0.2

  voxelize:
    max_num_points: 32
    voxel_size: &vsize
      [0.025, 0.025, 4]             # TBC
    max_voxels: [16000, 40000]      # [P_train, P_test]

  voxel_encoder:
    in_channels: 3
    feat_channels: [64]
    voxel_size: *vsize

  scatter:
    in_channels: 64
    output_shape: [496, 432]

  backbone:
    in_channels: 64
    out_channels: [64, 128, 256]
    layer_nums: [3, 5, 5]
    layer_strides: [2, 2, 2]

  neck:
    in_channels: [64, 128, 256]
    out_channels: [128, 128, 128]
    upsample_strides: [1, 2, 4]
    use_conv_for_no_stride: false

  head:
    in_channels: 384
    feat_channels: 384
    nms_pre: 100
    score_thr: 0.1
    ranges: [                   # TBC
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0],
      [-3, -3, 0, 3, 3, 0]
    ]
    sizes: [
        [0.6, 0.8, 1.73], [0.6, 1.76, 1.73], [1.6, 3.9, 1.56],
        [0.6, 0.8, 1.73], [0.6, 1.76, 1.73], [1.6, 3.9, 1.56],
        [0.6, 0.8, 1.73], [0.6, 1.76, 1.73], [1.6, 3.9, 1.56],
        [0.6, 0.8, 1.73], [0.6, 1.76, 1.73], [1.6, 3.9, 1.56],
        [0.6, 0.8, 1.73], [0.6, 1.76, 1.73], [1.6, 3.9, 1.56],
        [0.6, 0.8, 1.73], [0.6, 1.76, 1.73], [1.6, 3.9, 1.56]
    ]  # TBC
    rotations: [0, 1.57]
    iou_thr: [
        [0.35, 0.5], [0.35, 0.5], [0.45, 0.6],
        [0.35, 0.5], [0.35, 0.5], [0.45, 0.6],
        [0.35, 0.5], [0.35, 0.5], [0.45, 0.6],
        [0.35, 0.5], [0.35, 0.5], [0.45, 0.6],
        [0.35, 0.5], [0.35, 0.5], [0.45, 0.6],
        [0.35, 0.5], [0.35, 0.5], [0.45, 0.6],
    ]                # TBC

  augment:
    PointShuffle: True
    ObjectRangeFilter: True

pipeline:
  name: ObjectDetection
  test_compute_metric: true
  batch_size: 1
  val_batch_size: 1
  save_ckpt_freq: 5
  max_epoch: 200
  main_log_dir: ./logs
  train_sum_dir: train_log
  grad_clip_norm: 2

  optimizer:
    lr: 0.001
    betas: [0.95, 0.99]
    weight_decay: 0.01

  # evaluation properties
  overlaps: [
      0.5, 0.5, 0.7,
      0.5, 0.5, 0.7,
      0.5, 0.5, 0.7,
      0.5, 0.5, 0.7,
      0.5, 0.5, 0.7,
      0.5, 0.5, 0.7
  ]                     # TBC
  similar_classes: {
  }
  difficulties: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
